#!/usr/bin/with-contenv /bin/bash
set -ex

# flow cmd wrapper to execute flow as user
FLOW="sudo -u www-data FLOW_CONTEXT=${FLOW_CONTEXT} ./flow"

echo "127.0.0.1 behat.dev.local" >> /etc/hosts

/setup-behat-yml.sh "behat.dev.local:${WWW_PORT}"

# root dir where SITE_PACKAGE repo resides
WWW_ROOT="/data/www"

cd ${WWW_ROOT} || exit 1

if [ ${FLOW} help | grep behat:setup >/dev/null ; then
	${FLOW} behat:setup
	${FLOW} cache:warmup
fi
